[workspace]
members = [
    "./crates/controller",
    "./crates/planner",
    "./crates/recoder",
    "./crates/robot",
    "./crates/simulator",
    "./crates/solver",
    "./crates/task_manager",
    "./crates/temp",
    "crates/massage",
]

[workspace.package]
repository = "https://github.com/Robot-Exp-Platform/Robot-Platform"

[package]
name = "robot_platform"
version = "0.1.0"
edition = "2021"
# edition = "2024"
build = "build.rs"

[workspace.dependencies]
serde = { version = '*', features = ["derive"] }
serde_json = "*"
nalgebra = "*"
typenum = "*"
rosrust = '*'
rosrust_msg = '*'
zmq = "*"
zeromq = "*"
crossbeam = "*"

robot = { path = "./crates/robot" }
controller = { path = "./crates/controller" }
planner = { path = "./crates/planner" }
recoder = { path = "./crates/recoder" }
task_manager = { path = "./crates/task_manager" }
simulator = { path = "./crates/simulator" }
massage = { path = "./crates/massage" }

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
nalgebra.workspace = true
crossbeam.workspace = true
zmq = { workspace = true, optional = true }
rosrust = { workspace = true, optional = true }
rosrust_msg = { workspace = true, optional = true }

robot.workspace = true
controller.workspace = true
planner.workspace = true
recoder.workspace = true
task_manager.workspace = true
simulator.workspace = true
massage.workspace = true


[build-dependencies]


[features]
# default = ["rszmq"]
default = ["ros"]
# default = ["ros2"]
rszmq = [
    "zmq",
    "task_manager/rszmq",
    "controller/rszmq",
    "planner/rszmq",
    "simulator/rszmq",
]
noros = [
    "task_manager/noros",
    "controller/noros",
    "planner/noros",
    "simulator/noros",
]
ros = [
    "rosrust",
    "rosrust_msg",
    "task_manager/ros",
    "controller/ros",
    "planner/ros",
    "simulator/ros",
    "massage/ros",
]
ros2 = [
    "task_manager/ros2",
    "controller/ros2",
    "planner/ros2",
    "simulator/ros2",
]
