[workspace]
members = [
    "./crates/controller",
    "./crates/planner",
    "./crates/recoder",
    "./crates/robot",
    "./crates/simulator",
    "./crates/solver",
    "./crates/task_manager",
    "./crates/temp",
]

[workspace.package]
repository = "https://github.com/Robot-Exp-Platform/Robot-Platform"

[package]
name = "robot_platform"
version = "0.1.0"
edition = "2021"
# edition = "2024"
build = "build.rs"

[workspace.dependencies]
serde = { version = '*', features = ["derive"] }
serde_json = "*"
nalgebra = "*"
typenum = "*"
rosrust = '*'
rosrust_msg = '*'

robot = { path = "./crates/robot" }
controller = { path = "./crates/controller" }
planner = { path = "./crates/planner" }
recoder = { path = "./crates/recoder" }
task_manager = { path = "./crates/task_manager" }
simulator = { path = "./crates/simulator" }

[dependencies]
serde = { version = '*', features = ["derive"] }
serde_json = "*"
nalgebra = "*"
rosrust = { version = "*" }
rosrust_msg = { version = "*" }


robot = { path = "./crates/robot" }
controller = { path = "./crates/controller" }
planner = { path = "./crates/planner" }
recoder = { path = "./crates/recoder" }
task_manager = { path = "./crates/task_manager" }
simulator = { path = "./crates/simulator" }

[build-dependencies]


[features]
default = ["ros"]
# default = ["ros2"]
noros = [
    "task_manager/noros",
    "controller/noros",
    "planner/noros",
    "simulator/noros",
]
ros = ["task_manager/ros", "controller/ros", "planner/ros", "simulator/ros"]
ros2 = [
    "task_manager/ros2",
    "controller/ros2",
    "planner/ros2",
    "simulator/ros2",
]
