[workspace]
members = [
    "crates/controller",
    "crates/planner",
    "crates/recoder",
    "crates/robot",
    "crates/simulator",
    "crates/solver",
    "crates/task_manager",
    "crates/temp",
]

[package]
name = "robot_platform"
version = "0.1.0"
edition = "2021"
# edition = "2024"
build = "build.rs"

[features]
# default = ["ros"]
# default = ["ros2"]
noros = []
ros = []
ros2 = []

[dependencies]
robot = { path = "crates/robot" }
controller = { path = "crates/controller" }
planner = { path = "crates/planner" }
recoder = { path = "crates/recoder" }
task_manager = { path = "crates/task_manager" }


serde = { version = '*', features = ["derive"] }
serde_json = "*"
nalgebra = "*"
