[workspace]
members = ["src/generate_tools", "src/message", "src/robot"]

[workspace.package]
repository = "https://github.com/Robot-Exp-Platform/Robot-Platform"

[package]
name = "robot_platform"
version = "0.1.0"
edition = "2021"
# edition = "2024"

[workspace.dependencies]
serde = { version = '*', features = ["derive"] }
serde_json = "*"
serde_yaml = "*"
nalgebra = { version = "*", features = ["serde-serialize"] }
typenum = "*"
rosrust = '*'
rosrust_msg = '*'
zmq = "*"
zeromq = "*"
crossbeam = "*"
rand = "*"
chrono = "*"
lazy_static = "*"
approx = "*"
osqp = "*"
optimization_engine = "0.9.1"

message = { path = "src/message" }
robot = { path = "src/robot" }
generate_tools = { path = "src/generate_tools" }

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_yaml.workspace = true
nalgebra.workspace = true
crossbeam.workspace = true
rand.workspace = true
chrono.workspace = true
approx.workspace = true
zmq = { workspace = true, optional = true }
rosrust = { workspace = true, optional = true }
rosrust_msg = { workspace = true, optional = true }
osqp.workspace = true

[build-dependencies]


[features]
ros = []
ros2 = []
rszmq = []
