[package]
name = "massage"
version = "0.1.0"
edition = "2021"
repository.workspace = true

[dependencies]
nalgebra.workspace = true

rosrust = { workspace = true, optional = true }

[features]
ros = ["rosrust"]
