[package]
name = "message"
version = "0.1.0"
edition = "2021"
repository.workspace = true

[dependencies]
nalgebra.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json.workspace = true
rosrust = { workspace = true, optional = true }

[features]
ros = ["rosrust"]
