[package]
name = "message"
version = "0.1.0"
edition = "2021"
repository.workspace = true

[dependencies]
nalgebra.workspace = true
rosrust = { workspace = true, optional = true }

robot.workspace = true

[features]
ros = ["rosrust"]
