[package]
name = "task_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
nalgebra = { workspace = true }

robot = { workspace = true }

[features]
noros = []
ros = []
ros2 = []
