[package]
name = "simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
robot = { path = "../robot" }
task_manager = { path = "../task_manager" }
nalgebra = "*"
typenum = "*"
